### ISSUE TITLE
Create Cloud Formation

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#11]
Create Cloud Formation for all AWS component

- Cloud formation document are stored in GitHub repo (keep release)
- One file by Lamda (parser Geonames, parser Google, caller, regex, ...)

**Comment by David-Henandez-nrcan** [comment]
The information about the implementation of the application in AWS cloud services is included in this document.

[Geolocator_2023.docx](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator/files/11004141/Geolocator_2023.docx)
