### ISSUE TITLE
Create schemas for API call and response

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#13]
We should create a scheme that explain all queries

- Query sent to any of the API
- Query sent to our AWS API
- Response sent by any of the API
- Response sent by out API after parsing

**Comment by David-Henandez-nrcan** [comment]
There are two sets of schemas inside the repertory 'schemas' as well as in the AWS S3 bucket. those set are:
* Api. Two schemas are inside this section. 
    - in-api-schema. Defines the rules to validate the application's url parameters as well as the options for 'available services'
    - out-api-schema. It defines the mandatory fields to make any returned feature valid, the constrains for numeric fields, and finally the valid services available. 
* services. This branch contains the schemas for several services. Some are available, some might be in the future.
