### ISSUE TITLE
Deploy GitHub action

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#17]
See @bo-lu for more information on how to deploy our API

**Comment by David-Henandez-nrcan** [comment]
Succeeded to deploy a few API's associated to Lambda functions to gain understanding of AWS platform.
such as:

_import json
import urllib.request

def lambda_handler(event, context):
    # TODO implement
    queryStringParameters = event['queryStringParameters']
    query = queryStringParameters['q']
    print(queryStringParameters)
    print(query)
    return {
        'statusCode': 200,
        'body': json.dumps(queryStringParameters)
    }_
