### ISSUE TITLE
Create standard response functionality

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#18]
Create a function to parse every respond  from API/Data source to the standard response. Apply same technique as the parser functionality (schema, lookup, ...)

The goal is to be able to add new sources with a minimum of developers intervention. Use the response schema to build the output.

**Comment by David-Henandez-nrcan** [comment]
A python library called 'model_manager.py' inside cloud-formation/python includes all the functionality to parse every response from several API data sources  into standard response. the main function inside this library is: 
items_from_service().
it takes several parameters:
* service: The name of the service to put it ahead of the item's data
* model: The model schema with tables to extract from
* schema_items: the section of the out-api schema to process the data layer
* schema_required: The section of the out-api schema to validate the
* presence of 'required' fields in the data layer
* load: The input set of data items

The returning set of features complains with the expected standard response schema.
