### ISSUE TITLE
Investigate custom source approach and management

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#22]
Investigate how we will handle the custom source approach. When we do not have an API to query, look at what would be the way of handling items like NTS, watershed names, other info ...

Do we need to have
- GeoJSON in a S3 bucket to query against
- Database in the cloud
- Web service like OGC Feature API
- OpenSearch API

Take note of the steps to accomplish the creation
- Create file-database-service
- Create the input output schema
- Add the key to valid API key
- Create parser Lambda (or if we can standardize custom source, just reuse the available lambda
- Update documentation

** NOTE ** Add relevant information to this issue

**Comment by David-Henandez-nrcan** [comment]
Several tests using GraphQL show that (once implemented properly) using this tool will improve the efficiency and versatility of the application.

**Comment by David-Henandez-nrcan** [comment]
GraphQL was discarded early on the project due to the timing.

Must of the steps were accomplished using the following:
* Schema files in Json format for input/output and services in a S3 bucket.
* Lambda and API Gateway in AWS cloud service
* updated documentation
