### ISSUE TITLE
Create Nominatim input and response schema

### ISSUE THREAD

**Issue by jolevesq** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#29]
Use [Nominatim](https://nominatim.org/) open source API instead of Google for the moment.

Interface to test: https://nominatim.openstreetmap.org/ui/search.html?q=ottawa

Sample query: https://nominatim.openstreetmap.org/search?q=ottawa&format=json

**Comment by David-Henandez-nrcan** [comment]
Once modified the lambda function, its API has Nominatim included and responding:
https://ngnxf545cb.execute-api.ca-central-1.amazonaws.com/dev?address=ottawa&ids=geogratis,nominatim
