### ISSUE TITLE
Caching using Lambda ephemeral storage

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/GeoView-API-Geolocator#53]
Similar to [#29](https://github.com/Canadian-Geospatial-Platform/app.geo.ca/issues/29), we can add caching to this API using AWS Lambda ephemeral storage to enable caching of popular search terms. Implementation details are up to you, but an example of how it could be implemented can be found in 29.

Reference: https://blog.devgenius.io/aws-lambda-caching-why-and-how-bd3c2d500c

**Comment by David-Henandez-nrcan** [comment]
After analyzing carefully the characteristics of the load data from several services and examples. It was evident that using cache technic was not the best approach to accelerate the processing response, due to the low diversity and high variability of the data obtained.
